music_project/urls.py
from django.contrib import admin
from django.urls import path, include
from quiz_app import views as views1
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views1.show_basic, name="basic"),
    path('quiz_app/', include('quiz_app.urls')),

]

quiz_app/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'quiz_app'
urlpatterns = [
    path('main/', views.show_mainpage, name = 'quiz_mainpage'),

]

quiz_app/models.py
from django.db import models

# Create your models here.
import os
os.system('pip install requests')
import requests
import datetime
import base64
from urllib.parse import urlencode

client_id = "1b24afb4761649179023db1f4a95b37a"
client_secret = "8d3a958aa1b34aa6981f572a30b8a5c7"

class SpotifyAPI(object):

    access_token = None
    access_token_expires = None
    access_token_did_expire = True
    client_id = None
    client_secret = None
    token_url = "https://accounts.spotify.com/api/token"

    def __init__(self, client_id, client_secret, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.client_id = client_id
        self.client_secret = client_secret

    def get_client_credentials(self):
        """
        returns a base64 encoded STRING
        """
        client_id = self.client_id
        client_secret = self.client_secret
        if client_secret == None or client_id == None:
            raise Exception("YOU MUST SET CLIENT_ID AND CLIENT_SECRET")
        client_creds = f"{client_id}:{client_secret}"
        client_creds_b64 = base64.b64encode(client_creds.encode())
        return client_creds_b64.decode()

    def get_token_headers(self):
        client_creds_b64 = self.get_client_credentials()
        return {
            "Authorization":f"Basic {client_creds_b64}"
        }

    def get_token_data(self):
        return {
            "grant_type":"client_credentials",
        }

    def perform_auth(self):
        token_url = self.token_url
        token_data = self.get_token_data()
        token_headers = self.get_token_headers()

        r = requests.post(token_url, data=token_data, headers=token_headers)

        if r.status_code in range(200,299):
            print("REQUEST VALID")
            data=r.json()
            now = datetime.datetime.now()
            access_token = data['access_token']
            self.access_token = access_token
            expires_in = data['expires_in'] #seconds
            expires = now + datetime.timedelta(seconds=expires_in)
            self.access_token_expires = expires
            did_expire = expires < now
            self.access_token_did_expire = did_expire

            return True

        return False

spotify = SpotifyAPI(client_id, client_secret)
spotify.perform_auth()
access_token = spotify.access_token

headers = {
    "Authorization":f"Bearer {access_token}"
}

genres_endpoint = "https://api.spotify.com/v1/recommendations/available-genre-seeds"
genres_url = f"{genres_endpoint}?"
genres_r = requests.get(genres_url,headers=headers)
interesting_indexes = [0,1,4,5,8,16,17,18,20,21,26,27,30,31,32,33,34,37,38,44,46,47,48,49,51,52,53,55,64,66,67,68,69,70,73,77,80,81,83,85,86,95,97,98,99,100,102,103,104,105,110,114,115,116,120,-2,-1]
genres = []
for index in interesting_indexes:
    genres.append(genres_r.json()['genres'][index])


class User(models.Model):
    values = [x for x in genres]
    values_name = [x.capitalize() for x in genres]
    STYLE_CHOICES_L = [('-','-')]
    for x in range(0,len(genres)):
        STYLE_CHOICES_L.append((values[x],values_name[x]))
    STYLE_CHOICES = tuple(STYLE_CHOICES_L)
    ENERGY = ((0.8,'Turn Up'),(0.5,'Chill'),(0.3,'Study'))
    name = models.CharField(max_length=100, default=" ")
    style1 = models.CharField(max_length=100,choices = STYLE_CHOICES, default=STYLE_CHOICES[0])
    style2 = models.CharField(max_length=100,choices = STYLE_CHOICES, default=STYLE_CHOICES[0])
    style3 = models.CharField(max_length=100,choices = STYLE_CHOICES, default=STYLE_CHOICES[0])
    artist = models.CharField(max_length=1000, default=" ")
    mood = models.FloatField(max_length=1000,choices = ENERGY, default=ENERGY[0])
    linked_track = models.CharField(max_length=1000, default=" ")

    def __str__(self):
        return self.name+' (style: '+self.style1+', mood: '+self.mood+')'

quiz_app/forms.py
from django.forms import ModelForm
from . import models

class UserForm(ModelForm):
    class Meta:
        model = models.User
        fields = ["name","style1","style2","style3","artist","mood","linked_track"]

quiz_app/views.py
from django.shortcuts import render
from quiz_app.forms import UserForm
from music_app.models import Artist
from music_app.models import Music
import random
import os
os.system('pip install requests')
os.system('pip install Pillow')
import requests
import datetime
import base64
from urllib.parse import urlencode

client_id = "1b24afb4761649179023db1f4a95b37a"
client_secret = "8d3a958aa1b34aa6981f572a30b8a5c7"

class SpotifyAPI(object):

    access_token = None
    access_token_expires = None
    access_token_did_expire = True
    client_id = None
    client_secret = None
    token_url = "https://accounts.spotify.com/api/token"

    def __init__(self, client_id, client_secret, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.client_id = client_id
        self.client_secret = client_secret

    def get_client_credentials(self):
        """
        returns a base64 encoded STRING
        """
        client_id = self.client_id
        client_secret = self.client_secret
        if client_secret == None or client_id == None:
            raise Exception("YOU MUST SET CLIENT_ID AND CLIENT_SECRET")
        client_creds = f"{client_id}:{client_secret}"
        client_creds_b64 = base64.b64encode(client_creds.encode())
        return client_creds_b64.decode()

    def get_token_headers(self):
        client_creds_b64 = self.get_client_credentials()
        return {
            "Authorization":f"Basic {client_creds_b64}"
        }

    def get_token_data(self):
        return {
            "grant_type":"client_credentials",
        }

    def perform_auth(self):
        token_url = self.token_url
        token_data = self.get_token_data()
        token_headers = self.get_token_headers()

        r = requests.post(token_url, data=token_data, headers=token_headers)

        if r.status_code in range(200,299):
            print("REQUEST VALID")
            data=r.json()
            now = datetime.datetime.now()
            access_token = data['access_token']
            self.access_token = access_token
            expires_in = data['expires_in'] #seconds
            expires = now + datetime.timedelta(seconds=expires_in)
            self.access_token_expires = expires
            did_expire = expires < now
            self.access_token_did_expire = did_expire

            return True

        return False

spotify = SpotifyAPI(client_id,client_secret)
spotify.perform_auth()
access_token = spotify.access_token

headers = {
    "Authorization":f"Bearer {access_token}"
}
# Create your views here.
def show_basic(request):
    return render(request,'quiz_app/basic.html')


def index(request):
    return render(request,'quiz_app/homepage.html')


def show_music_page(request, form_instance):

    cleaned_data = super(UserForm, form_instance).clean()
    print(cleaned_data)
    recommendation_endpoint = "https://api.spotify.com/v1/recommendations"

    energy = float(cleaned_data['mood'])
    print(energy)

    genres_list = [cleaned_data['style1']]
    if cleaned_data['style2'] != "-":
        genres_list.append(cleaned_data['style2'])
    if cleaned_data['style3'] != "-":
        genres_list.append(cleaned_data['style3'])
    print(genres_list)
    recommendation_data = {"seed_genres":genres_list,"target_energy":energy}
    if cleaned_data["artist"] != "0" and cleaned_data["artist"] != "":
        search_endpoint = "https://api.spotify.com/v1/search"
        search_data = urlencode({"q":cleaned_data['artist'], "type":"artist","limit":1})
        search_url = f"{search_endpoint}?{search_data}"
        ##print(search_url)
        search_r = requests.get(search_url, headers=headers,)
        #3print(search_r.status_code)
        ##print(search_r.json())
        ##print(search_r.json()['artists']['items'][0]['name'])
        artist_id_str = search_r.json()['artists']['items'][0]['id']
        artist_name = search_r.json()['artists']['items'][0]['name']
        ##print(artist_id_str)
        recommendation_data["seed_artists"] = artist_id_str

    if cleaned_data["linked_track"] != "0" and cleaned_data["linked_track"] != "":
        search_endpoint = "https://api.spotify.com/v1/search"
        search_data = urlencode({"q":cleaned_data['linked_track'], "type":"track","limit":1})
        search_url = f"{search_endpoint}?{search_data}"
        search_r = requests.get(search_url, headers=headers)
        linked_track_id_str = search_r.json()['tracks']['items'][0]['id']
        linked_track_id_name = search_r.json()['tracks']['items'][0]['name']
        recommendation_data["seed_tracks"] = linked_track_id_str


    recommendation_data_url = urlencode(recommendation_data)
    recommendation_url=f"{recommendation_endpoint}?{recommendation_data_url}"
    ##print(recommendation_url)
    recommendation_r = requests.get(recommendation_url,headers=headers,)


    print(recommendation_r.json())
    ##for r in recommendation_r.json()['tracks']:

        ##print(recommendation_r.status_code)
        ##print(r['name'])
        ##print(r['artists'][0]['name'])
    a_dict = {"music":[]}
    Artist.objects.all().delete()
    Music.objects.all().delete()
    for r in recommendation_r.json()['tracks']:
        artists = Artist.objects.get_or_create(name=r['artists'][0]['name'],)[0]
        musics = Music.objects.get_or_create(artist=artists,style=genres_list,mood=energy,title=r['name'],link=r['external_urls']['spotify'])[0]


    if cleaned_data["artist"] != "0" and cleaned_data["artist"] != "" and cleaned_data["linked_track"] != "0" and cleaned_data["linked_track"] != "":
        a_dict = {"music":Music.objects.order_by("mood"),"seed_artist":artist_name,"seed_track":linked_track_id_name}

    elif cleaned_data["artist"] != "0" and cleaned_data["artist"] != "":
        a_dict = {"music":Music.objects.order_by("mood"),"seed_artist":artist_name}

    elif cleaned_data["linked_track"] != "0" and cleaned_data["linked_track"] != "":
        a_dict = {"music":Music.objects.order_by("mood"),"seed_track":linked_track_id_name}

    else:
        print("ERROR NO ARTIST NO TRACK")

    return render(request,'quiz_app/musicpage.html',context=a_dict)


def show_mainpage(request):
    form_instance = UserForm()
    if request.method == 'POST':
        print(request.POST)
        form_instance = UserForm(request.POST)

        if form_instance.is_valid():
            form_instance.save()
            return show_music_page(request,form_instance)

        else:
            print("problem")
    ##return render(request,'quiz_app/homepage.html')
    return render(request,'quiz_app/homepage.html')

templates/quiz_app/basic.html
<!DOCTYPE html>
{%load static%}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <link rel="stylesheet" href="{%static 'quiz_app/quiz_app.css'%}">
  <body>


      {% block body_block%}
      <!-- ANYTHING OUTSIDE OF THIS WILL BE INHERITED IF EXTENDED-->
      <div class="">
        <br>
        <br>
        <br>
        <br>

        <h1 class="display-3 text-white">Welcome to the Music recommender!</h1>
        <br>
        <br>
        <h4 class="display5 text-white"> So, you are looking for your new favorite music?</h4>
        <br>
        <br>
        <br>
        <br>
        <a href="{% url 'quiz_app:quiz_mainpage' %}"><button class = "btn btn-success btn-lg"type="button" name="button">Get me one!</button></a>

      </div>
      {% endblock %}

  </body>
</html>

templates/quiz_app/homepage.html
<!DOCTYPE html>
{%extends "quiz_app/basic.html"%}
{%block body_block%}
<div class="container text-center">
    <br>
    <br>
    <br>

    <h4 class='text-white display-4'>Okay, please enter your name and the type of music you are looking for!</h4>

    <br>
    <br>

    <div class="text-white ">
    <form method="post">

      <div class="form-group">
        <label for="id_name">Name*:</label>
        <input type="text" class="form-control" name="name" id="id_name" value="">
      </div>

      <br>
      <br>

      <div class="form-group">
        <label for="id_style1">Style one*:</label> <select class="form-control" name="style1" required id="id_style1">
          <option value="-" selected>-</option>

          <option value="acoustic">Acoustic</option>

          <option value="afrobeat">Afrobeat</option>

          <option value="ambient">Ambient</option>

          <option value="anime">Anime</option>

          <option value="blues">Blues</option>

          <option value="chill">Chill</option>

          <option value="classical">Classical</option>

          <option value="club">Club</option>

          <option value="country">Country</option>

          <option value="dance">Dance</option>

          <option value="disco">Disco</option>

          <option value="disney">Disney</option>

          <option value="dubstep">Dubstep</option>

          <option value="edm">Edm</option>

          <option value="electro">Electro</option>

          <option value="electronic">Electronic</option>

          <option value="emo">Emo</option>

          <option value="french">French</option>

          <option value="funk">Funk</option>

          <option value="groove">Groove</option>

          <option value="guitar">Guitar</option>

          <option value="happy">Happy</option>

          <option value="hard-rock">Hard-rock</option>

          <option value="hardcore">Hardcore</option>

          <option value="heavy-metal">Heavy-metal</option>

          <option value="hip-hop">Hip-hop</option>

          <option value="holidays">Holidays</option>

          <option value="house">House</option>

          <option value="j-pop">J-pop</option>

          <option value="jazz">Jazz</option>

          <option value="k-pop">K-pop</option>

          <option value="kids">Kids</option>

          <option value="latin">Latin</option>

          <option value="latino">Latino</option>

          <option value="metal">Metal</option>

          <option value="movies">Movies</option>

          <option value="new-release">New-release</option>

          <option value="opera">Opera</option>

          <option value="party">Party</option>

          <option value="piano">Piano</option>

          <option value="pop">Pop</option>

          <option value="rainy-day">Rainy-day</option>

          <option value="reggaeton">Reggaeton</option>

          <option value="road-trip">Road-trip</option>

          <option value="rock">Rock</option>

          <option value="rock-n-roll">Rock-n-roll</option>

          <option value="romance">Romance</option>

          <option value="sad">Sad</option>

          <option value="salsa">Salsa</option>

          <option value="samba">Samba</option>

          <option value="sleep">Sleep</option>

          <option value="spanish">Spanish</option>

          <option value="study">Study</option>

          <option value="summer">Summer</option>

          <option value="techno">Techno</option>

          <option value="work-out">Work-out</option>

          <option value="world-music">World-music</option>

        </select>
      </div>

      <br>
      <br>

      <div class="form-group">
        <label for="id_style2">Style two (optional): </label> <select class="form-control" name="style2" id="id_style2">
          <option value="-" selected>-</option>

          <option value="acoustic">Acoustic</option>

          <option value="afrobeat">Afrobeat</option>

          <option value="ambient">Ambient</option>

          <option value="anime">Anime</option>

          <option value="blues">Blues</option>

          <option value="chill">Chill</option>

          <option value="classical">Classical</option>

          <option value="club">Club</option>

          <option value="country">Country</option>

          <option value="dance">Dance</option>

          <option value="disco">Disco</option>

          <option value="disney">Disney</option>

          <option value="dubstep">Dubstep</option>

          <option value="edm">Edm</option>

          <option value="electro">Electro</option>

          <option value="electronic">Electronic</option>

          <option value="emo">Emo</option>

          <option value="french">French</option>

          <option value="funk">Funk</option>

          <option value="groove">Groove</option>

          <option value="guitar">Guitar</option>

          <option value="happy">Happy</option>

          <option value="hard-rock">Hard-rock</option>

          <option value="hardcore">Hardcore</option>

          <option value="heavy-metal">Heavy-metal</option>

          <option value="hip-hop">Hip-hop</option>

          <option value="holidays">Holidays</option>

          <option value="house">House</option>

          <option value="j-pop">J-pop</option>

          <option value="jazz">Jazz</option>

          <option value="k-pop">K-pop</option>

          <option value="kids">Kids</option>

          <option value="latin">Latin</option>

          <option value="latino">Latino</option>

          <option value="metal">Metal</option>

          <option value="movies">Movies</option>

          <option value="new-release">New-release</option>

          <option value="opera">Opera</option>

          <option value="party">Party</option>

          <option value="piano">Piano</option>

          <option value="pop">Pop</option>

          <option value="rainy-day">Rainy-day</option>

          <option value="reggaeton">Reggaeton</option>

          <option value="road-trip">Road-trip</option>

          <option value="rock">Rock</option>

          <option value="rock-n-roll">Rock-n-roll</option>

          <option value="romance">Romance</option>

          <option value="sad">Sad</option>

          <option value="salsa">Salsa</option>

          <option value="samba">Samba</option>

          <option value="sleep">Sleep</option>

          <option value="spanish">Spanish</option>

          <option value="study">Study</option>

          <option value="summer">Summer</option>

          <option value="techno">Techno</option>

          <option value="work-out">Work-out</option>

          <option value="world-music">World-music</option>

        </select>
      </div>

      <br>
      <br>

      <div class="form-group">
        <label for="id_style3">Style three (optional):</label> <select class="form-control" name="style3" id="id_style3">
          <option value="-" selected>-</option>

          <option value="acoustic">Acoustic</option>

          <option value="afrobeat">Afrobeat</option>

          <option value="ambient">Ambient</option>

          <option value="anime">Anime</option>

          <option value="blues">Blues</option>

          <option value="chill">Chill</option>

          <option value="classical">Classical</option>

          <option value="club">Club</option>

          <option value="country">Country</option>

          <option value="dance">Dance</option>

          <option value="disco">Disco</option>

          <option value="disney">Disney</option>

          <option value="dubstep">Dubstep</option>

          <option value="edm">Edm</option>

          <option value="electro">Electro</option>

          <option value="electronic">Electronic</option>

          <option value="emo">Emo</option>

          <option value="french">French</option>

          <option value="funk">Funk</option>

          <option value="groove">Groove</option>

          <option value="guitar">Guitar</option>

          <option value="happy">Happy</option>

          <option value="hard-rock">Hard-rock</option>

          <option value="hardcore">Hardcore</option>

          <option value="heavy-metal">Heavy-metal</option>

          <option value="hip-hop">Hip-hop</option>

          <option value="holidays">Holidays</option>

          <option value="house">House</option>

          <option value="j-pop">J-pop</option>

          <option value="jazz">Jazz</option>

          <option value="k-pop">K-pop</option>

          <option value="kids">Kids</option>

          <option value="latin">Latin</option>

          <option value="latino">Latino</option>

          <option value="metal">Metal</option>

          <option value="movies">Movies</option>

          <option value="new-release">New-release</option>

          <option value="opera">Opera</option>

          <option value="party">Party</option>

          <option value="piano">Piano</option>

          <option value="pop">Pop</option>

          <option value="rainy-day">Rainy-day</option>

          <option value="reggaeton">Reggaeton</option>

          <option value="road-trip">Road-trip</option>

          <option value="rock">Rock</option>

          <option value="rock-n-roll">Rock-n-roll</option>

          <option value="romance">Romance</option>

          <option value="sad">Sad</option>

          <option value="salsa">Salsa</option>

          <option value="samba">Samba</option>

          <option value="sleep">Sleep</option>

          <option value="spanish">Spanish</option>

          <option value="study">Study</option>

          <option value="summer">Summer</option>

          <option value="techno">Techno</option>

          <option value="work-out">Work-out</option>

          <option value="world-music">World-music</option>

        </select>
      </div>

        <br>
        <br>
        <div class="row">

        <div class="form-group col">
          <label for="id_artist">An artist that you like (leave 0 if none): </label>
          <input class="form-control" id="id_artist" type="text" name="artist" value="0">
        </div>

        <div class="form-group col">
          <label for="id_linked_track">Or a track that you like (leave 0 if none): </label>
          <input class="form-control" id="id_linked_track" type="text" name="linked_track" value="0">
          <p class = "text-white">(Do not hesitate to copy-paste tracks from Spotify, since it is our database)</p>
        </div>
        </div>

        <br>
        <br>

      <div class="form-group">
        <label for="id_mood">Mood:</label> <select class="form-control" name="mood" id="id_mood">
          <option value="0.8" selected>Turn Up</option>

          <option value="0.5">Chill</option>

          <option value="0.3">Study</option>

        </select>
      </div>

        <br>
        <br>
        <br>
        <br>
        {% csrf_token %}
        <input class="btn btn-success"type="submit" name="" value="Get me my music!">
</form>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
</div>

</div>
{%endblock%}

templates/quiz_app/musicpage.html
<!DOCTYPE html>
{%extends "quiz_app/basic.html"%}
{%block body_block%}

    <div class="container-lg">


    <br>
    <br>
    <br>

    {%if seed_artist and seed_track%}
    <h1 class="text-white">Okay, so according to your previous choices</h1><h1 class="text-white">we recommend you the following song:</h1><br><h4 class="text-white">(The seed artist being {{seed_artist}} and the seed track being {{seed_track}}),</h4><br>

    {%elif seed_artist%}
    <h1 class="text-white">Okay, so according to your previous choices</h1><h1 class="text-white"> we recommend you the following song:</h1><br><h4 class="text-white">(The seed artist being {{seed_artist}}),</h4><br>

    {%elif seed_track%}
    <h1 class="text-white">Okay, so according to your previous choices</h1><h1 class="text-white"> we recommend you the following song:</h1><br><h4 class="text-white">(The seed track being {{seed_track}}),</h4><br>

    {%endif%}
    <p class="form-text text-white">(This is a random choice from a database, which means you will may other recommendations with the same choices)</p>
    <br>
    <br>
    <br>
    {%if music%}
    <div class="container">
    <table class="text-white table table-bordered">
      <thead>
        <tr>
          <th scope="col">Recommended tracks:</th>
          <th scope="col">Artists</th>
          <th scope="col">Links</th>
        </tr>
      </thead>
      <tbody>
        {%for m in music%}
        <tr>
          <td>{{m.title}}</td>
          <td>{{m.artist}}</td>
          <td class = "text-white"><a href="{{m.link}}">Spotify Link</a></td>
        </tr>
        {%endfor%}
      </tbody>
    </table>
    </div>
    {%endif%}
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
{%endblock%}